#!/bin/bash

. scripts/lib/common.sh

#
# recomendado correr siempre
# parametros y cia.
#
SEED_FILE=$2

[ ! -f $SEED_FILE ] && echo "Seed data not found: $SEED_FILE" && exit 2

export PGPASSWORD=$PASSWORD
set -x
psql -h $HOST -p $PORT -U $USERNAME -d $DB -f $SEED_FILE
check_status $?

