#!/bin/bash

. scripts/lib/common.sh

echo "[PGSQL] Dropping DB: $DB"
psql -h $HOST -p $PORT -U $USERNAME -d template1 -c "drop database if exists $DB"
check_status $?
echo "[PGSQL] Creating DB: $DB"
psql -h $HOST -p $PORT -U $USERNAME -d template1 -c "create database $DB"
check_status $?

