#!/bin/bash

. scripts/lib/common.sh

#
# recomendado correr siempre
# parametros y cia.
#
SEED_MINIMUN=db/seed-data-minimum_testing.sql
SEED_FILE=db/seed-data.sql

[ ! -f $SEED_MINIMUM ] && echo "Seed data not found: $SEED_MINIMUM" && exit 2
[ ! -f $SEED_DATA ] && echo "Seed data not found: $SEED_DATA" && exit 2

if [  "$SODEP" == "si" ] ; then
	echo "Estoy en SODEP"
	SEED_MINIMUN=db/seed-data-minimum_at_sodep.sql
else
	echo "NO estoy en Sodep $MY_IP"
    if [ $MY_IP == "10.9.10.4" ]; then
        SEED_MINIMUN=db/seed-data-minimum_stagging.sql
    fi
fi

export PGPASSWORD=$PASSWORD
set -x
psql -h $HOST -p $PORT -U $USERNAME -d $DB -f $SEED_MINIMUN
check_status $?
psql -h $HOST -p $PORT -U $USERNAME -d $DB -f $SEED_FILE
check_status $?

